language: go

go:
  - 1.6.x
  - 1.7.x
  - 1.8.x
  - 1.9.x

# Install glide
addons:
  apt:
    sources:
    - sourceline: 'ppa:masterminds/glide'
    packages:
    - glide

install:
  - make setup

script:
  - make test
  - make build-all
